apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "ui" | trunc 63 | quote }}
  labels:
    {{- include "dealership-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dealership-ui.selectorLabels" . | nindent 4 }}
