stages:
  - containerize
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

container:
  stage: containerize
  image: docker:20
  services:
    - docker:20-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - export TAG_NAME=$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
    - docker build --build-arg DEALERSHIPAPI=$DEALERSHIPAPI -t $TAG_NAME .
    - docker push $TAG_NAME
    - docker inspect --format='{{index .RepoDigests 0}}' $TAG_NAME > .image_name
  artifacts:
    paths:
      - .image_name
    expire_in: 30 days
  only:
    - develop
    - main
    - tag

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache wget curl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - wget https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
    - tar -xvf helm-v3.6.3-linux-amd64.tar.gz
    - mv linux-amd64/helm .
  script:
    - ./helm upgrade dealership-ui ./charts/dealership-ui --install --set image_name=$(cat .image_name) --history-max 2
